// Papel y Luna POS — API Google Sheets (MVP 2)
const SPREADSHEET_ID="1kmzh-YbSZKIZHOwXe6hb-08s_YD2gHpcnPdnWFpd_Y0";
const H={productos:["id","codigo","nombre","categoriaId","precio","costo","seguimientoInventario","stock"],ventas:["id","fecha","estado","clienteId","metodoPago","subtotal","total","valorRecibido","cambio","itemsJson","actualizadoEn"],compras:["id","fecha","proveedorId","total","itemsJson"],clientes:["id","nombre","telefono","correo"],proveedores:["id","nombre","telefono","correo"],categorias:["id","nombre"]};
function setupPOS(){const b=SpreadsheetApp.openById(SPREADSHEET_ID);Object.keys(H).forEach(n=>{let s=b.getSheetByName(n)||b.insertSheet(n);if(!s.getLastRow())s.getRange(1,1,1,H[n].length).setValues([H[n]]);else{const h=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0];if(H[n].some((x,i)=>h[i]!==x))throw Error("Encabezados incorrectos en "+n+". Esperados: "+H[n].join(", "));}s.setFrozenRows(1);s.getRange(1,1,1,H[n].length).setFontWeight("bold").setBackground("#70566d").setFontColor("#ffffff");});return "Se crearon las seis pestañas con sus encabezados.";}
function doGet(e){try{return out({success:true,data:read_(resource_(e))});}catch(x){return out({success:false,message:String(x.message||x)});}}
function doPost(e){const lock=LockService.getScriptLock();let held=false;try{const n=resource_(e),b=JSON.parse(e.postData.contents||"{}");if(!b.action||!b.data)throw Error("Se requieren action y data.");lock.waitLock(10000);held=true;let d=b.data,r;if(b.action==="create")r=create_(n,d);else if(b.action==="update")r=update_(n,d);else if(b.action==="delete")r=remove_(n,d);else throw Error("Acción no permitida.");return out({success:true,data:r});}catch(x){return out({success:false,message:String(x.message||x)});}finally{if(held)lock.releaseLock();}}
function resource_(e){const n=e&&e.parameter&&e.parameter.resource;if(!H[n])throw Error("Recurso faltante o no permitido: "+n);return n;}
function sheet_(n){const s=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(n);if(!s)throw Error("Falta la pestaña "+n+"; ejecuta setupPOS().");return s;}
function heads_(s){return s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0];}
function row_(s,id){const h=heads_(s),c=h.indexOf("id")+1;if(!c)throw Error("Falta encabezado id.");const n=s.getLastRow();if(n<2)return -1;const a=s.getRange(2,c,n-1,1).getDisplayValues();for(let i=0;i<a.length;i++)if(String(a[i][0])===String(id))return i+2;return -1;}
function read_(n){const a=sheet_(n).getDataRange().getValues();if(!a.length)return [];const h=a[0];return a.slice(1).filter(r=>r.some(v=>v!=="")).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i] instanceof Date?r[i].toISOString():r[i]);return o;});}
function write_(s,o,h,row){const r=s.getRange(row||s.getLastRow()+1,1,1,h.length),v=h.map(k=>o[k]===undefined||o[k]===null?"":typeof o[k]==="object"?JSON.stringify(o[k]):o[k]);v.forEach((x,i)=>{if(typeof x==="string")r.getCell(1,i+1).setNumberFormat("@");});r.setValues([v]);}
function create_(n,d){if(!d.id)throw Error("El registro requiere id.");const s=sheet_(n);if(row_(s,d.id)>0)throw Error("El id ya existe.");write_(s,d,heads_(s));return d;}
function update_(n,d){if(!d.id)throw Error("La actualización requiere id.");const s=sheet_(n),r=row_(s,d.id);if(r<0)throw Error("No existe el registro.");const h=heads_(s),a=s.getRange(r,1,1,h.length).getValues()[0],o={};h.forEach((k,i)=>o[k]=a[i]);Object.keys(d).forEach(k=>{if(h.includes(k))o[k]=d[k];});write_(s,o,h,r);return o;}
function remove_(n,d){const s=sheet_(n),r=row_(s,d.id);if(r<0)throw Error("No existe el registro.");s.deleteRow(r);return {id:d.id};}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
