export const money=n=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(Number(n)||0);
export const dateText=s=>{if(!s)return "—";const d=new Date(s);return Number.isNaN(d.valueOf())?String(s):new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(d)};
export const id=()=>crypto.randomUUID();
export const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
export const sumItems=items=>items.reduce((a,i)=>a+(Number(i.precio??i.costo)||0)*(Number(i.cantidad)||0),0);
export const parseItems=v=>{try{return Array.isArray(v)?v:JSON.parse(v||"[]")}catch{return []}};
export function toast(message,type="info"){const n=document.querySelector("#notice");n.textContent=message;n.className=`notice ${type}`;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,4500)}
export function field(label,name,value="",opts={}){const type=opts.type||"text",required=opts.required!==false;return `<div class="field ${opts.full?"full":""}"><label for="f-${name}">${esc(label)}${required?" *":""}</label>${opts.options?`<select id="f-${name}" name="${name}" ${required?"required":""}>${opts.options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?"selected":""}>${esc(o.label)}</option>`).join("")}</select>`:`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${opts.placeholder?`placeholder="${esc(opts.placeholder)}"`:""} ${type==="number"?`min="0" step="${opts.step||1}"`:""} ${required?"required":""}>`}</div>`}
export function formData(form){return Object.fromEntries(new FormData(form).entries())}
export function printInvoice(sale){const items=parseItems(sale.itemsJson);const w=window.open("","_blank","width=720,height=800");if(!w){toast("Permite ventanas emergentes para imprimir la factura.","error");return}w.document.write(`<!doctype html><html lang="es"><meta charset="utf-8"><title>Factura ${esc(sale.id)}</title><style>body{font:14px Arial,sans-serif;max-width:650px;margin:35px auto;color:#222}h1{font:26px Georgia;text-align:center}p{text-align:center;color:#666}.rule{border-top:1px solid #ddd;margin:20px 0}table{width:100%;border-collapse:collapse}td,th{padding:10px 4px;border-bottom:1px solid #ddd;text-align:left}td:last-child,th:last-child{text-align:right}.total{text-align:right;font-weight:bold;font-size:18px;margin-top:18px}@media print{button{display:none}}</style><h1>Papel y Luna</h1><p>Comprobante de venta</p><div class="rule"></div><p style="text-align:left">Venta: ${esc(sale.id)}<br>Fecha: ${esc(dateText(sale.fecha))}<br>Cliente: ${esc(sale.clienteNombre||"Venta general")}<br>Pago: ${esc(sale.metodoPago||"—")}</p><table><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.nombre)}</td><td>${Number(i.cantidad)||0}</td><td>${money(i.precio)}</td><td>${money((Number(i.precio)||0)*(Number(i.cantidad)||0))}</td></tr>`).join("")}</tbody></table><div class="total">Total: ${money(sale.total)}</div><p>Gracias por tu compra</p><script>window.onload=()=>window.print()<\/script></html>`);w.document.close()}
